name: gn37
channels:
  - conda-forge
dependencies:
  - python=3.7 # need ipython 6.5.0 as higher do not autocomlete
  - pip=22.1
  - requests=2.27.1
  - numpy=1.21.6 # don't care of specific numpy and pandas versions
  - pandas=1.1.0 #MongoDash required version
  - matplotlib=3.5.2
  - ruamel.yaml=0.17.21
  - wget=1.20.3
  - boto3=1.23.1
  - ipython=6.5.0 #need this version
  - notebook>=5.3 #MongoDash
  - ipywidgets>=7.2 #MongoDash
  - pymongo=3.7.2 #MongoDash
  - pytest=7.1.2
  - scipy=1.7.3
  - statsmodels=0.13.2
  - pip:
      - sklearn==0.0
      - dash==2.0.0
      - plotly==5.3.1
      - tqdm==4.64.0  #useful for long processing sessions
      - git+https://github.com/bmatv/python-unlzw.git # memory leak patched
      - plotext==4.2
      - requests_oauthlib==1.3.1
      - werkzeug==2.0.3

