var searchData=
[
  ['geomagmainfield_0',['GeomagMainField',['../structGeomagMainField.html',1,'']]],
  ['geomagsecularvariation_1',['GeomagSecularVariation',['../structGeomagSecularVariation.html',1,'']]],
  ['geph_2',['Geph',['../structGeph.html',1,'']]],
  ['gepoch_3',['GEpoch',['../structGEpoch.html',1,'']]],
  ['getsnxresult_4',['GetSnxResult',['../unionGetSnxResult.html',1,'']]],
  ['ginar_5fmtx_5',['GinAR_mtx',['../structGinAR__mtx.html',1,'']]],
  ['ginar_5fopt_6',['GinAR_opt',['../structGinAR__opt.html',1,'']]],
  ['globaloptions_7',['GlobalOptions',['../structGlobalOptions.html',1,'']]],
  ['gobs_8',['GObs',['../structGObs.html',1,'']]],
  ['gobsmeta_9',['GObsMeta',['../structGObsMeta.html',1,'']]],
  ['gptgrid_10',['GptGrid',['../structGptGrid.html',1,'']]],
  ['gptvals_11',['GPTVals',['../structGPTVals.html',1,'']]],
  ['gridmap_12',['GridMap',['../structGridMap.html',1,'']]],
  ['gtime_13',['GTime',['../structGTime.html',1,'']]],
  ['gtow_14',['GTow',['../structGTow.html',1,'']]],
  ['gweek_15',['GWeek',['../structGWeek.html',1,'']]]
];
