clear;

mission = 'SPIRE';

ephFile = 'SPIRE_2023.001.124.11.xyz';              % retrieved from ephemeris, e.g. SP3, SCA, etc.
attFile = 'SPIRE_2023.001.124.11_att.att';          % generated by debugAttitude()
gifFile = 'SPIRE_2023.001.124.11_body(att).gif';    % output gif file

ephUnit = 1e3;      % unit of ephemeris: km == 1e3, m == 1

scaleEarth = 0.2;   % scale factor of plotted Earth
scaleAxis  = 1e6;   % scale factor of plotted axes

delay = 0.05;       % animation refresh interval

eph = load(ephFile);
t  = eph(:,1:2);            % GPS time
r  = eph(:,3:5)*ephUnit;	% sat pos

att = load(attFile);
eX = att(:, 3: 5);
eY = att(:, 6: 8);
eZ = att(:, 9:11);
eS = att(:,21:23);          % eSun

dX = eX*scaleAxis;
dY = eY*scaleAxis;
dZ = eZ*scaleAxis;
dS = eS*scaleAxis;

X = r + dX;
Y = r + dY;
Z = r + dZ;
S = r + dS;

figure('unit', 'normalized', 'position', [0, 0, 1, 1]);
hold on;
axis equal;
axis off;
box off;

RE = 6371000*scaleEarth;

load topo;
axesm('globe', 'grid', 'on', 'galtitude', RE);
meshm(topo, topolegend, [], RE);
demcmap(topo);
view(135, 30);

title = title(mission);

orbit = plot3(r(1,1), r(1,2), r(1,3), 'c');
sat   = scatter3(r(1,1), r(1,2), r(1,3), 'filled');
radial= plot3([0; r(1,1)], [0; r(1,2)], [0; r(1,3)], 'm--');

quiver3(0, 0, 0, RE*2, 0, 0, 'r');
quiver3(0, 0, 0, 0, RE*2, 0, 'g');
quiver3(0, 0, 0, 0, 0, RE*2, 'b');

text(RE*2, 0, 0, 'X_E_C_E_F');
text(0, RE*2, 0, 'Y_E_C_E_F');
text(0, 0, RE*2, 'Z_E_C_E_F');

axisX = quiver3(r(1,1), r(1,2), r(1,3), dX(1,1), dX(1,2), dX(1,3), 'r');
axisY = quiver3(r(1,1), r(1,2), r(1,3), dY(1,1), dY(1,2), dY(1,3), 'g');
axisZ = quiver3(r(1,1), r(1,2), r(1,3), dZ(1,1), dZ(1,2), dZ(1,3), 'b');
eSun  = quiver3(r(1,1), r(1,2), r(1,3), dS(1,1), dS(1,2), dS(1,3), 'y');

textX = text(X(1,1), X(1,2), X(1,3), 'X_b');
textY = text(Y(1,1), Y(1,2), Y(1,3), 'Y_b');
textZ = text(Z(1,1), Z(1,2), Z(1,3), 'Z_b');
textS = text(S(1,1), S(1,2), S(1,3), 'eSun');

eR(1,:) = r(1,:)/norm(r(1,:));

info  = sprintf('GPS Week: %d\nSec of Week: %8.1f\nSat Pos: %12.3f %12.3f %12.3f\neSun: %9.6f %9.6f %9.6f\neX_b: %9.6f %9.6f %9.6f\neY_b: %9.6f %9.6f %9.6f\neZ_b: %9.6f %9.6f %9.6f\neZ_b*eSat = %9.6f\neY_b*eSun = %9.6f', ...
    t (1,1), t (1,2), ...
    r (1,1), r (1,2), r (1,3), ...
    eS(1,1), eS(1,2), eS(1,3), ...
    eX(1,1), eX(1,2), eX(1,3), ...
    eY(1,1), eY(1,2), eY(1,3), ...
    eZ(1,1), eZ(1,2), eZ(1,3), ...
    dot(eZ(1,:), eR(1,:)), ...
    dot(eY(1,:), eS(1,:)));

dash  = annotation('textbox', [0.7 0.8 0 0], 'string', info, 'fitboxtotext', 'on');

for i = 1:10:length(t)
    
    eR(i,:) = r(i,:)/norm(r(i,:));
    
    info  = sprintf('GPS Week: %d\nSec of Week: %8.1f\nSat Pos: %12.3f %12.3f %12.3f\neSun: %9.6f %9.6f %9.6f\neX_b: %9.6f %9.6f %9.6f\neY_b: %9.6f %9.6f %9.6f\neZ_b: %9.6f %9.6f %9.6f\neZ_b*eSat = %9.6f\neY_b*eSun = %9.6f', ...
        t (i,1), t (i,2), ...
        r (i,1), r (i,2), r (i,3), ...
        eS(i,1), eS(i,2), eS(i,3), ...
        eX(i,1), eX(i,2), eX(i,3), ...
        eY(i,1), eY(i,2), eY(i,3), ...
        eZ(i,1), eZ(i,2), eZ(i,3), ...
        dot(eZ(i,:), eR(i,:)), ...
        dot(eY(i,:), eS(i,:)));
    set(dash, 'string', info);
    
    set(orbit, 'xdata', r(1:i,1), 'ydata', r(1:i,2), 'zdata', r(1:i,3));
    set(sat,   'xdata', r(i,1),   'ydata', r(i,2),   'zdata', r(i,3));
    set(radial,'xdata', [0; r(i,1)], 'ydata', [0; r(i,2)], 'zdata', [0; r(i,3)]);
    
    set(axisX, 'xdata', r(i,1), 'ydata', r(i,2), 'zdata', r(i,3), 'udata', dX(i,1), 'vdata', dX(i,2), 'wdata', dX(i,3));
    set(axisY, 'xdata', r(i,1), 'ydata', r(i,2), 'zdata', r(i,3), 'udata', dY(i,1), 'vdata', dY(i,2), 'wdata', dY(i,3));
    set(axisZ, 'xdata', r(i,1), 'ydata', r(i,2), 'zdata', r(i,3), 'udata', dZ(i,1), 'vdata', dZ(i,2), 'wdata', dZ(i,3));
    set(eSun,  'xdata', r(i,1), 'ydata', r(i,2), 'zdata', r(i,3), 'udata', dS(i,1), 'vdata', dS(i,2), 'wdata', dS(i,3));
    
    set(textX, 'position', [X(i,1), X(i,2), X(i,3)]);
    set(textY, 'position', [Y(i,1), Y(i,2), Y(i,3)]);
    set(textZ, 'position', [Z(i,1), Z(i,2), Z(i,3)]);
    set(textS, 'position', [S(i,1), S(i,2), S(i,3)]);
    
    pause(delay);
    
    frame = getframe(gcf);
    im = frame2im(frame);
    [imind, cm] = rgb2ind(im, 256);
    if i == 1
        imwrite(imind, cm, gifFile, 'gif', 'loopcount', inf, 'delaytime', delay);
    else
        imwrite(imind, cm, gifFile, 'gif', 'writemode', 'append', 'delaytime', delay);
    end
end
