#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include "common/receiver.hpp"
#include "common/zhangCheckpoint.hpp"
#include "pea/zhangInputCheckpoint.hpp"
#include "pea/zhangReceiverCheckpoint.hpp"
#include "pea/zhangReference.hpp"

struct Navigation;

/** Infra-0 permits no persistent pseudo-random engine.  Algorithms may derive
 * an epoch-local seed from immutable inputs, but there is then no RNG cursor
 * that a restart could omit. */
inline constexpr std::uint32_t ZHANG_E29_RNG_CHECKPOINT_SCHEMA_VERSION = 1;
inline constexpr const char* ZHANG_E29_RNG_CHECKPOINT_SECTION_NAME =
	"pea.rng_declaration.v1";
inline constexpr const char* ZHANG_E29_RNG_CHECKPOINT_PAYLOAD =
	"no persistent RNG; epoch-local deterministic seeds only";

inline constexpr const char* ZHANG_E29_CHECKPOINT_BUNDLE_FILENAME =
	"checkpoint.bundle";
inline constexpr const char* ZHANG_E29_CHECKPOINT_MANIFEST_FILENAME =
	"checkpoint_manifest.json";
inline constexpr const char* ZHANG_E29_CHECKPOINT_EXPERIMENT_MODE =
	"E29_GPS_L1C_L2W_ZHANG_FULL_RANK";

/** Exact executable/configuration/input provenance for capture or restore.
 * ABI fingerprints and endianness are generated by the orchestrator itself;
 * callers cannot weaken those gates. */
struct ZhangE29CheckpointProvenance
{
	std::string experimentMode =
		ZHANG_E29_CHECKPOINT_EXPERIMENT_MODE;
	std::string binaryPath;
	std::string configText;
	std::string inputManifestText;
};

struct ZhangE29CheckpointIdentity
{
	std::string runtimeId;
	std::string checkpointId;
	std::string parentCheckpointId;
	/** ISO-8601 UTC.  Empty means generate it at capture time. */
	std::string createdUtc;
};

struct ZhangE29CheckpointResult
{
	bool valid = false;
	std::string failureReason;
	std::string checkpointId;
	std::string runtimeId;
	std::string payloadSha256;
	std::uint64_t payloadBytes = 0;
	std::size_t sectionCount = 0;
	int stateDimension = 0;
	/** A commit error after the first module swap is fatal to the process.  The
	 * flag distinguishes it from a side-effect-free read/preflight failure. */
	bool liveStateMayBePartial = false;
};

/** Opaque-by-convention two-phase restore token.  It retains the module plans
 * whose importers can stage decoded objects and a digest binding it to the
 * exact outer bundle. */
struct ZhangE29CheckpointRestorePlan
{
	bool valid = false;
	std::string bundleIdentitySha256;
	std::string checkpointId;
	std::string runtimeId;
	int stateDimension = 0;

	ZhangPeaControllerCheckpointRestorePlan controller;
	ZhangRinexFileStreamsCheckpointRestorePlan rinexStreams;
	ZhangReceiverRuntimeCheckpointRestorePlan receivers;
	ZhangSatelliteRuntimeCheckpointRestorePlan satellites;

	std::size_t pppArPendingTransitions = 0;
	std::size_t pppArPendingSnapshotPins = 0;
	std::size_t ambresActiveTemporalTransitions = 0;
};

/** The registry is exact, not merely a list of optional extensions.  Restore
 * rejects missing, additional, renamed, or version-skewed sections. */
const std::vector<ZhangCheckpointSectionRequirement>&
zhangE29CheckpointRequiredSections();

/** Capture all Infra-0 state at POST_EPOCH_COMMITTED.  The authoritative KF
 * must already be bound to identity.runtimeId.  No file is written. */
ZhangE29CheckpointResult captureZhangE29CheckpointBundle(
	const KFState& authoritativeState,
	const ReceiverMap& receivers,
	const Navigation& navigation,
	const std::multimap<std::string, StreamParserPtr>& streams,
	const std::map<std::string, bool>& streamDoneMap,
	const ZhangPeaControllerCheckpointState& controller,
	const ZhangE29CheckpointIdentity& identity,
	const ZhangE29CheckpointProvenance& provenance,
	ZhangCheckpointBundle& bundle);

/** Publish one immutable directory containing the binary bundle and its JSON
 * manifest.  Both files are first completed in a sibling staging directory;
 * publishing is one directory rename. */
ZhangE29CheckpointResult writeZhangE29CheckpointDirectory(
	const std::string& targetDirectory,
	const ZhangCheckpointBundle& bundle);

ZhangE29CheckpointResult captureAndWriteZhangE29Checkpoint(
	const std::string& targetDirectory,
	const KFState& authoritativeState,
	const ReceiverMap& receivers,
	const Navigation& navigation,
	const std::multimap<std::string, StreamParserPtr>& streams,
	const std::map<std::string, bool>& streamDoneMap,
	const ZhangPeaControllerCheckpointState& controller,
	const ZhangE29CheckpointIdentity& identity,
	const ZhangE29CheckpointProvenance& provenance,
	ZhangCheckpointBundle* capturedBundle = nullptr);

/** Read the authoritative binary from an atomically published directory and
 * apply exact executable/config/input/ABI/runtime gates. */
ZhangE29CheckpointResult readZhangE29CheckpointDirectory(
	const std::string& checkpointDirectory,
	const ZhangE29CheckpointProvenance& provenance,
	const std::string& expectedRuntimeId,
	ZhangCheckpointBundle& bundle);

/** Validate every section and reconstruct a candidate KF core without
 * changing live state.  The PPP-AR snapshot inventory and both modules'
 * transition endpoints are joined before any commit; dangling identities or
 * inconsistent declared reference counts fail closed. */
ZhangE29CheckpointResult preflightZhangE29CheckpointBundle(
	const ZhangCheckpointBundle& bundle,
	const ZhangE29CheckpointProvenance& provenance,
	KFState& configuredState,
	const ReceiverMap& configuredReceivers,
	const Navigation& configuredNavigation,
	const std::multimap<std::string, StreamParserPtr>& configuredStreams,
	const std::map<std::string, bool>& configuredStreamDoneMap,
	double expectedEpochIntervalSeconds,
	ZhangE29CheckpointRestorePlan& plan);

/** Re-run the complete preflight, then commit in dependency order:
 * satellite identities, receivers, stream cursors/queues, KF core, graph,
 * PPP-AR, ambiguity runtime, callback rebinding, and controller last. */
ZhangE29CheckpointResult commitZhangE29CheckpointBundle(
	const ZhangCheckpointBundle& bundle,
	const ZhangE29CheckpointProvenance& provenance,
	KFState& authoritativeState,
	ReceiverMap& receivers,
	Navigation& navigation,
	std::multimap<std::string, StreamParserPtr>& streams,
	std::map<std::string, bool>& streamDoneMap,
	const ZhangE29CheckpointRestorePlan& plan,
	ZhangPeaControllerCheckpointState& restoredController);
