"""
Controller for the YAML configuration tab.

Manages the following UI widgets and behaviours:
  - "Show Config" button
  - "Reset Config" button
  - "Overwrite Config with UI Values" toggle switch (Determines how the config file is written to)
  - Opening the GinanYAMLInspector
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path
from PySide6.QtCore import Qt, QUrl, QObject, Slot
from PySide6.QtWidgets import QFileDialog, QDialog, QVBoxLayout, QMessageBox
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebEngineCore import QWebEngineSettings, QWebEngineDownloadRequest
from PySide6.QtWebChannel import QWebChannel
from scripts.GinanUI.app.models.inspector import Inspector
from scripts.GinanUI.app.utils.common_dirs import GENERATED_YAML, INSPECTOR_HTML_PATH
from scripts.GinanUI.app.utils.logger import Logger
from scripts.GinanUI.app.utils.toast import show_toast

class _InspectorBridge(QObject):
    """
    Qt object exposed to the GinanYAMLInspector page via QWebChannel.

    The inspector's "Save file" button is intercepted by injected JavaScript
    which calls bridge.saveYaml(yamlText) instead of triggering a file download.
    This allows Ginan-UI to write the YAML directly to ppp_generated.yaml and
    notify the user without any file-picker dialog.
    """

    def __init__(self, yaml_config_ctrl: "YAMLConfigController", parent=None):
        super().__init__(parent)
        self._ctrl = yaml_config_ctrl

    @Slot(str)
    def saveYaml(self, yaml_text: str):
        """
        Receive YAML text from the inspector page and write it to ppp_generated.yaml.
        Called from JavaScript when the user clicks "Save file" in the inspector.

        Arguments:
          yaml_text (str): The raw YAML string generated by the inspector.
        """
        self._ctrl._on_inspector_save(yaml_text)


class YAMLConfigController:
    """
    Manages the YAML configuration tab: output file type checkboxes.

    Arguments:
      ui: The main window UI instance.
      input_ctrl: The parent InputController instance (for accessing shared state).
    """

    def __init__(self, ui, input_ctrl):
        """
        Initialise output config tab bindings.

        Arguments:
          ui: The main window UI instance.
          input_ctrl: The parent InputController that owns shared state.
        """
        self.ui = ui
        self.ctrl = input_ctrl  # parent InputController

        # Button wiring
        self.ui.showConfigButton.clicked.connect(self.on_show_config)
        self.ui.showConfigButton.setCursor(Qt.CursorShape.PointingHandCursor)
        self.ui.resetConfigButton.clicked.connect(self._on_reset_config_clicked)
        self.ui.editConfigInInspectorButton.clicked.connect(self.open_inspector)

        # Keep a reference to the open inspector dialog (if any) to avoid garbage collection
        self._inspector_dialog: QDialog | None = None

        # Bridge object for QWebChannel (inspector -> Python "Save file" interception)
        self._bridge: _InspectorBridge | None = None

        # Inspector model: handles all non-UI work (HTML generation, JS building, YAML sanitisation / merging / writing)
        # It is instantiated by _get_inspector()
        # so the executable from the Execution model is resolved at first use rather
        # than at controller construction time
        self._inspector: Inspector | None = None

        # Initial button states
        self.ui.showConfigButton.setEnabled(False)

    def _get_inspector(self) -> Inspector:
        """
        Return the Inspector model singleton instance, creating it on first access if it doesn't already exist

        The PEA executable is taken from the Execution model so the inspector
        can auto-generate its HTML asset via "pea -Y 4" when missing.

        Returns:
          Inspector: The shared Inspector model instance.
        """
        if self._inspector is None:
            executable = getattr(self.ctrl.execution, "executable", None)
            self._inspector = Inspector(executable=executable)
        return self._inspector

    #region UI Tooltips

    def setup_tooltips(self):
        """
        Set up tooltips for all Output config tab widgets.
        """
        self.ui.yamlOverwriteCheckbox.setToolTip(
            "Enable / disable overwriting the YAML config file with the values specified here within Ginan-UI."
            "\nUseful for manual changes that Ginan-UI would otherwise overwrite."
        )
        self.ui.showConfigButton.setToolTip(
            "Generate and open the YAML configuration file.\n"
            "You can review and modify advanced settings before processing.\n"
            "Note: UI defined parameters will ALWAYS override manual config edits."
        )
        self.ui.resetConfigButton.setToolTip(
            "Delete and regenerate the YAML configuration file and start from a clean slate.\n"
            "Note: Will delete all modifications to the existing file!"
        )
        self.ui.editConfigInInspectorButton.setToolTip(
            "Open the YAML configuration file in the GinanYAMLInspector external tool\n"
            "Useful for large configuration changes that are not possible with what Ginan-UI exposes.\n"
            "The current config will be pre-loaded. Use 'Save file' in the Inspector to write changes back."
        )

    #endregion

    #region YAML Toggles

    def get_yaml_toggles(self) -> bool:
        """
        Read the current state of the YAML checkboxes

        Returns:
          bool: yaml_overwrite
        """
        yaml_overwrite = self.ui.yamlOverwriteCheckbox.isChecked() if hasattr(self.ui, "yamlOverwriteCheckbox") else True
        return yaml_overwrite

    #endregion

    #region Config Handling

    def on_show_config(self):
        """
        UI handler: reload config, apply UI values, write changes, then open the YAML.
        If YAML overwrite is disabled, skip applying UI values and just open the file.
        """
        Logger.workflow("📄 Opening YAML configuration file...")
        yaml_overwrite = self.get_yaml_toggles()

        if yaml_overwrite:
            self.ctrl.execution.reload_config()
            inputs = self.ctrl.extract_ui_values(self.ctrl.rnx_file)
            self.ctrl.execution.apply_ui_config(inputs)
            self.ctrl.execution.write_cached_changes()

        # Execution class will throw error when instantiated if the file doesn't exist and it can't create it
        # This code is run after Execution class is instantiated within this file, thus never will occur
        if not os.path.exists(GENERATED_YAML):
            QMessageBox.warning(
                None,
                "File not found",
                f"The file {GENERATED_YAML} does not exist."
            )
            return

        self._open_config_in_editor(self.ctrl.config_path)

    def _open_config_in_editor(self, file_path):
        """
        Open the config YAML file in the OS default editor/viewer.

        Arguments:
          file_path (str): Absolute or relative path to the YAML file.
        """
        import platform

        try:
            abs_path = os.path.abspath(file_path)

            # Open the file with the appropriate method for the operating system
            if platform.system() == "Windows":
                os.startfile(abs_path)
                return

            if platform.system() == "Darwin":  # macOS
                subprocess.run(["open", abs_path])

            else:  # Linux and other Unix-like systems
                # When compiled with pyinstaller, LD_LIBRARY_PATH is modified which prevents external app opening
                env = os.environ.copy()
                original = env.get("LD_LIBRARY_PATH_ORIG")
                if original:
                    env["LD_LIBRARY_PATH"] = original  # Restore original value
                else:
                    env.pop("LD_LIBRARY_PATH", None)  # Clear the value to use sys defaults
                subprocess.run(["xdg-open", abs_path], env=env)

        except Exception as e:
            error_message = f"Cannot open config file:\n{file_path}\n\nError: {str(e)}"
            Logger.workflow(f"Error: {error_message}")
            QMessageBox.critical(None, "Error Opening File", error_message)

    def _on_reset_config_clicked(self):
        """
        UI handler: reset the configuration file and UI to defaults.
        Shows a confirmation dialog before proceeding.
        """
        reply = QMessageBox.question(
            self.ctrl.parent,
            "Reset Configuration",
            "This will reset all settings to their defaults.\n\n"
            "• The configuration file will be regenerated from the template\n"
            "• All UI fields will be cleared\n"
            "• You will need to re-select your RINEX file and output directory\n\n"
            "Are you sure you want to continue?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No
        )

        if reply != QMessageBox.StandardButton.Yes:
            return

        try:
            self.ctrl.stop_all()
            self.ctrl.execution.reset_config()
            self.ctrl._reset_ui_to_defaults()
            Logger.workflow("🔄 Configuration and UI reset to defaults")
            show_toast(self.ctrl.parent, "🔄 Configuration and UI reset to defaults", duration=3000)

        except Exception as e:
            Logger.workflow(f"⚠️ Failed to reset configuration: {e}")
            QMessageBox.critical(self.ctrl.parent, "Reset Failed", f"Failed to reset configuration:\n{e}")

    #endregion

    #region Reset to Defaults

    def reset_to_defaults(self):
        """
        Reset all YAML config tab fields to their default states.
        """
        if hasattr(self.ui, 'yamlOverwriteCheckbox'):
            self.ui.yamlOverwriteCheckbox.setChecked(True)

    #endregion

    #region GinanYAMLInspector

    def _ui_is_ready(self) -> bool:
        """
        Return True if the UI has enough state populated to safely call extract_ui_values()

        Checks that a RINEX file has been selected and that the time window field contains
        a value that looks like a valid range (i.e. it contains " to "). This mirrors the
        minimum requirements of parse_time_window() so we avoid raising inside
        _prepare_config_for_inspector() when the user opens the inspector before loading a
        RINEX file

        Returns:
          bool: True if the UI is sufficiently populated for config extraction.
        """
        if not self.ctrl.rnx_file:
            return False
        time_window = self.ui.timeWindowValue.text() if hasattr(self.ui, "timeWindowValue") else ""
        return " to " in time_window

    def _prepare_config_for_inspector(self) -> bool:
        """
        Ensure ppp_generated.yaml is up-to-date before opening the inspector

        Applies UI values to the config if "Overwrite Config with UI Values" is enabled
        AND the UI has been fully populated (RINEX loaded, time window set). Otherwise
        falls back silently to whatever config is already on disk.

        Returns:
          bool: True if the config file is ready on disk, False on error.
        """
        yaml_overwrite = self.get_yaml_toggles()
        ui_ready = self._ui_is_ready()

        if yaml_overwrite and ui_ready:
            try:
                self.ctrl.execution.reload_config()
                inputs = self.ctrl.extract_ui_values(self.ctrl.rnx_file)
                self.ctrl.execution.apply_ui_config(inputs)
                self.ctrl.execution.write_cached_changes()
                Logger.workflow("📄 Config updated with current UI values for GinanYAMLInspector")
            except Exception as e:
                # Log but do not block - fall through to open with existing file
                Logger.workflow(f"⚠️ Could not apply UI values to config for GinanYAMLInspector: {e}")
        elif yaml_overwrite and not ui_ready:
            Logger.workflow("📄 RINEX not yet loaded - Opening GinanYAMLInspector with existing config file")
        else:
            Logger.workflow("📄 YAML overwrite disabled - Opening GinanYAMLInspector with existing config file")

        return GENERATED_YAML.exists()

    def _on_inspector_save(self, yaml_text: str):
        """
        Callback triggered when the user clicks "Save file" in the GinanYAMLInspector

        Delegates the sanitise / parse / merge / write / repair / fallback flow to the
        Inspector model and handles the UI-side feedback: toasts, error dialogs, reloading
        the Execution config, and repopulating the UI fields from the merged config so the
        UI stays in sync with what is now on disk.

        Arguments:
          yaml_text (str): Raw YAML string produced by the inspector's "Generate yaml" step
        """
        try:
            merged = self._get_inspector().merge_and_save(yaml_text)
        except ValueError as e:
            # Empty input or non-mapping output - show a toast and abort quietly
            show_toast(self.ctrl.parent, f"⚠️ Inspector save aborted: {e}", duration=4000)
            return
        except Exception as e:
            Logger.workflow(f"❌ Failed to save GinanYAMLInspector config: {e}")
            QMessageBox.critical(
                self.ctrl.parent,
                "Save Failed",
                f"Could not merge the inspector config with the existing file:\n{e}"
            )
            return

        # Reload the saved config into the Execution model
        reload_ok = False
        try:
            self.ctrl.execution.reload_config()
            Logger.workflow("🔄 Config reloaded from GinanYAMLInspector")
            reload_ok = True
        except Exception as e:
            Logger.workflow(f"⚠️ Config written to disk but Execution reload raised: {e}")

        # Repopulate UI fields from the merged config so the UI stays in sync.
        # Use the freshly reloaded execution config if available; otherwise fall back
        # to the merged dict we computed above so the UI still updates even when
        # the reload failed.
        ui_config = self.ctrl.execution.config if reload_ok else merged
        try:
            self.populate_ui_from_config(ui_config)
        except Exception as e:
            Logger.workflow(f"⚠️ Config saved but UI repopulation raised: {e}")

        show_toast(self.ctrl.parent, "✅ GinanYAMLInspector config saved", duration=4000)

    def populate_ui_from_config(self, config: dict):
        """
        Read values from a loaded YAML config dict and push them back into the
        relevant Ginan-UI widgets so the UI stays in sync after an inspector save

        Only fields that are present in the config are updated - missing keys are
        silently skipped so that partial inspector exports do not blank out fields
        that were not touched

        The following UI areas are covered:
          - Time window (start/end epoch) and epoch interval
          - Receiver type, antenna type, antenna offset, apriori position
          - GNSS constellation selection (General tab multi-select combo)
          - Observation code priorities per constellation (Constellation tab list widgets)
          - Output toggles (POS, GPX, TRACE, SNX)
          - Processing mode (Static / Kinematic / Dynamic / Custom via process_noise value)

        Arguments:
          config (dict): Loaded ruamel.yaml CommentedMap (or plain dict) from
                         ppp_generated.yaml after the inspector merge
        """
        ui = self.ui

        # Helper: safely navigate a nested dict by dot-path
        def _get(path: str, default=None):
            keys = path.split(".")
            node = config
            for k in keys:
                if not isinstance(node, dict) or k not in node:
                    return default
                node = node[k]
            return node

        # Time window
        start = _get("processing_options.epoch_control.start_epoch")
        end   = _get("processing_options.epoch_control.end_epoch")
        if start and end:
            # Normalise ruamel PlainScalarString / datetime objects to plain str
            start_str = str(start).strip("'\"").replace(" ", "_")
            end_str   = str(end).strip("'\"").replace(" ", "_")
            time_text = f"{start_str} to {end_str}"
            if hasattr(ui, "timeWindowButton"):
                ui.timeWindowButton.setText(time_text)
            if hasattr(ui, "timeWindowValue"):
                ui.timeWindowValue.setText(time_text)

        # Epoch interval
        interval = _get("processing_options.epoch_control.epoch_interval")
        if interval is not None:
            interval_text = f"{int(interval) if float(interval) == int(float(interval)) else float(interval)} s"
            if hasattr(ui, "dataIntervalButton"):
                ui.dataIntervalButton.setText(interval_text)
            if hasattr(ui, "dataIntervalValue"):
                ui.dataIntervalValue.setText(interval_text)

        # Receiver / antenna metadata
        # Look up the marker key that corresponds to the currently active RINEX file.
        # There can be multiple non-global keys under receiver_options (one per station);
        # we only update the UI fields when the key matches the active marker so we don't
        # accidentally populate values from a different station's block.
        # If no RINEX is loaded yet, fall back to the first non-global key found.
        receiver_options = _get("receiver_options", {})
        active_marker = None
        if self.ctrl.rnx_file:
            from scripts.GinanUI.app.controllers.input_controller import InputController
            active_marker = InputController.extract_marker_name(self.ctrl.rnx_file)

        def _find_marker_key(rec_opts: dict, preferred: str | None) -> str | None:
            """Return the receiver_options key to use for UI population.

            Tries preferred (active marker) first; falls back to the first
            non-global key if preferred is absent or no RINEX is loaded.
            """
            if preferred and preferred in rec_opts:
                return preferred
            return next((k for k in rec_opts if k != "global"), None)

        marker_key = _find_marker_key(receiver_options, active_marker)

        def _strip_yaml_comment(value: str) -> str:
            """Strip a trailing inline YAML comment from a plain-scalar value.

            The inspector copies the raw YAML line content including any inline
            comment, e.g. 'SEPT POLARXSSS # #USER_SET (string)'. Only the part
            before the first ' #' sequence is the actual value.
            """
            # Split on ' #' but not on '#' that appears inside a word (unlikely
            # in these fields, but safe to be conservative with the leading space).
            idx = value.find(' #')
            return value[:idx].strip() if idx != -1 else value.strip()

        if marker_key:
            rec_block = receiver_options[marker_key]

            receiver_type = rec_block.get("receiver_type") if isinstance(rec_block, dict) else None
            if receiver_type is not None:
                cleaned = _strip_yaml_comment(str(receiver_type))
                if cleaned:
                    # Mirror the same combo + label update that the popup dialog performs
                    if hasattr(ui, "receiverTypeCombo"):
                        ui.receiverTypeCombo.clear()
                        ui.receiverTypeCombo.addItem(cleaned)
                        if ui.receiverTypeCombo.lineEdit():
                            ui.receiverTypeCombo.lineEdit().setText(cleaned)
                    if hasattr(ui, "receiverTypeValue"):
                        ui.receiverTypeValue.setText(cleaned)

            antenna_type = rec_block.get("antenna_type") if isinstance(rec_block, dict) else None
            if antenna_type is not None:
                cleaned = _strip_yaml_comment(str(antenna_type))
                if cleaned:
                    # Mirror the same combo + label update that the popup dialog performs
                    if hasattr(ui, "antennaTypeCombo"):
                        ui.antennaTypeCombo.clear()
                        ui.antennaTypeCombo.addItem(cleaned)
                        if ui.antennaTypeCombo.lineEdit():
                            ui.antennaTypeCombo.lineEdit().setText(cleaned)
                    if hasattr(ui, "antennaTypeValue"):
                        ui.antennaTypeValue.setText(cleaned)

            # Antenna offset [E, N, U]
            offset = rec_block.get("models", {}).get("eccentricity", {}).get("offset") if isinstance(rec_block, dict) else None
            if offset and len(offset) == 3:
                offset_text = ", ".join(str(v) for v in offset)
                if hasattr(ui, "antennaOffsetButton"):
                    ui.antennaOffsetButton.setText(offset_text)
                if hasattr(ui, "antennaOffsetValue"):
                    ui.antennaOffsetValue.setText(offset_text)

            # Apriori position [X, Y, Z]
            apriori = rec_block.get("apriori_position") if isinstance(rec_block, dict) else None
            if apriori and len(apriori) == 3:
                apriori_text = ", ".join(str(v) for v in apriori)
                if hasattr(ui, "aprioriPositionButton"):
                    ui.aprioriPositionButton.setText(apriori_text)

        # GNSS constellation selection and code priorities
        # Both the General tab multi-select and the Constellation tab list widgets
        # are driven together from sys_options in the YAML.
        #
        # Constellation selection:
        #   _update_constellations_multiselect() rebuilds the checkable combo model
        #   with only the enabled constellations pre-checked, and internally calls
        #   sync_list_widgets_to_selection() to show/hide the per-constellation list
        #   widgets accordingly.
        #
        # Code priorities:
        #   _setup_list_widget() populates each QListWidget with the codes from the
        #   YAML's code_priorities list (in order). All items in that list are checked
        #   because the inspector only emits codes that were selected - unchecked codes
        #   from a previous RINEX load are not present in the YAML export and therefore
        #   are not shown at all after an inspector save.
        const_map = {
            "gps": ("GPS", "gpsListWidget"),
            "gal": ("GAL", "galListWidget"),
            "glo": ("GLO", "gloListWidget"),
            "bds": ("BDS", "bdsListWidget"),
            "qzs": ("QZS", "qzsListWidget"),
        }
        sys_options = _get("processing_options.gnss_general.sys_options", {})
        if isinstance(sys_options, dict):
            enabled_labels = [
                label
                for key, (label, _) in const_map.items()
                if sys_options.get(key, {}).get("process", False)
            ]

            # Rebuild the General tab constellation combo with the enabled set
            if enabled_labels:
                self.ctrl.general_tab._update_constellations_multiselect(
                    ", ".join(enabled_labels)
                )
            else:
                # No constellations enabled - clear the combo and show placeholder
                if hasattr(ui, "constellationsValue"):
                    ui.constellationsValue.setText("")
                self.ctrl.constellations_tab._update_placeholder(True)

            # Repopulate each constellation list widget from code_priorities
            for yaml_key, (label, widget_name) in const_map.items():
                if not hasattr(ui, widget_name):
                    continue
                list_widget = getattr(ui, widget_name)
                const_block = sys_options.get(yaml_key)
                if not isinstance(const_block, dict):
                    continue
                raw_codes = const_block.get("code_priorities")
                if raw_codes is None:
                    continue
                # Normalise to a plain list of uppercase strings
                codes = [str(c).strip() for c in raw_codes if str(c).strip()]
                if codes:
                    # All codes in the YAML list are the selected/checked ones -
                    # pass the same set as both the full list and the enabled set
                    self.ctrl.constellations_tab._setup_list_widget(
                        list_widget, codes, set(codes)
                    )
                else:
                    # Empty list - clear the widget but leave it enabled so the user
                    # can see that the constellation has no codes assigned
                    list_widget.clear()

        # Output toggles
        gpx_out   = _get("outputs.gpx.output")
        pos_out   = _get("outputs.pos.output")
        trace_out = _get("outputs.trace.output_network")
        snx_out   = _get("outputs.sinex.output")

        if gpx_out is not None and hasattr(ui, "gpxCheckbox"):
            ui.gpxCheckbox.setChecked(bool(gpx_out))
        if pos_out is not None and hasattr(ui, "posCheckbox"):
            ui.posCheckbox.setChecked(bool(pos_out))
        if trace_out is not None and hasattr(ui, "traceCheckbox"):
            ui.traceCheckbox.setChecked(bool(trace_out))
        if snx_out is not None and hasattr(ui, "snxCheckbox"):
            ui.snxCheckbox.setChecked(bool(snx_out))

        # Processing mode
        # Inferred from estimation_parameters.receivers.global.pos.process_noise:
        #   0   -> Static
        #   30  -> Kinematic
        #   100 -> Dynamic
        #   anything else -> Custom (shown as a non-standard label)
        #
        # modeCombo uses _bind_combo which repopulates ["Static", "Kinematic",
        # "Dynamic"] only when the user opens the dropdown. At rest the combo just
        # displays whatever text is in it, so we can set an arbitrary label by
        # clearing and adding a single item. The next time the user opens the popup
        # the standard items are restored normally by the bound showPopup hook.
        process_noise = _get("estimation_parameters.receivers.global.pos.process_noise")
        if process_noise is not None and hasattr(ui, "modeCombo"):
            try:
                noise_val = int(float(
                    process_noise[0]
                    if hasattr(process_noise, '__iter__') and not isinstance(process_noise, str)
                    else process_noise
                ))
                mode_label = {0: "Static", 30: "Kinematic", 100: "Dynamic"}.get(
                    noise_val, f"Custom ({noise_val})"
                )
                combo = ui.modeCombo
                combo.clear()
                combo.addItem(mode_label)
            except (TypeError, ValueError, IndexError):
                pass

    def open_inspector(self):
        """
        UI handler: open the GinanYAMLInspector in an embedded Qt dialog

        Before opening:
          1. The ppp_generated.yaml config is written/updated (if YAML overwrite is on)
          2. The inspector HTML is generated via "pea -Y 4" if it does not already exist

        Once loaded:
          - The current ppp_generated.yaml is auto-imported into the inspector's fields
          - The "Save file" button is intercepted so that saving merges the inspector
            output back onto ppp_generated.yaml (preserving keys the inspector omitted)
            rather than doing a destructive overwrite

        The inspector remains fully usable outside Ginan-UI - the Ginan-UI-specific
        behaviour (auto-import, save intercept) is only wired up when opened from here
        """
        inspector = self._get_inspector()

        # Step 1: Ensure config is up to date on disk
        config_ready = self._prepare_config_for_inspector()
        if not config_ready:
            QMessageBox.warning(
                self.ctrl.parent,
                "Config Not Found",
                f"The config file does not exist yet:\n{GENERATED_YAML}\n\n"
                "Please select a RINEX file first so the config can be generated."
            )
            return

        # Step 2: Ensure the inspector HTML exists
        if not inspector.ensure_inspector_html():
            QMessageBox.warning(
                self.ctrl.parent,
                "Inspector Not Available",
                f"The GinanYAMLInspector HTML file could not be found or generated.\n\n"
                f"Expected location:\n{INSPECTOR_HTML_PATH}\n\n"
                "You can generate it manually by running:\n"
                "  pea -Y 4\n"
                "and placing the output at the path above."
            )
            return

        Logger.workflow("🔍 Opening GinanYAMLInspector...")

        # Step 3: Read the YAML content now (before any async load completes)
        yaml_content = inspector.read_current_config()

        # Step 4: Build the inspector dialog
        dialog = QDialog(self.ctrl.parent)
        dialog.setWindowTitle("GinanYAMLInspector")
        dialog.setWindowFlags(
            Qt.WindowType.Window |
            Qt.WindowType.WindowMinimizeButtonHint |
            Qt.WindowType.WindowMaximizeButtonHint |
            Qt.WindowType.WindowCloseButtonHint
        )
        dialog.resize(1200, 800)
        dialog.setMinimumSize(600, 400)

        layout = QVBoxLayout(dialog)
        layout.setContentsMargins(0, 0, 0, 0)

        webview = QWebEngineView(dialog)

        settings = webview.settings()
        settings.setAttribute(QWebEngineSettings.WebAttribute.JavascriptEnabled, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.LocalContentCanAccessFileUrls, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.LocalContentCanAccessRemoteUrls, True)

        # Step 5: Set up QWebChannel so the page can call bridge.saveYaml()
        self._bridge = _InspectorBridge(self)
        channel = QWebChannel(webview.page())
        channel.registerObject("bridge", self._bridge)
        webview.page().setWebChannel(channel)

        # Step 6: Inject qwebchannel.js via QWebEngineScript so it is available before
        # any page script runs. This guarantees qt.webChannelTransport exists when our
        # setup JS calls new QWebChannel(...).
        from PySide6.QtWebEngineCore import QWebEngineScript
        qwc_script = QWebEngineScript()
        qwc_script.setName("qwebchannel_init")
        qwc_script.setSourceUrl(QUrl("qrc:///qtwebchannel/qwebchannel.js"))
        qwc_script.setInjectionPoint(QWebEngineScript.InjectionPoint.DocumentCreation)
        qwc_script.setWorldId(QWebEngineScript.ScriptWorldId.MainWorld)
        webview.page().scripts().insert(qwc_script)

        # Step 7: On load, run the Ginan-UI setup script (auto-import + save intercept)
        ginan_ui_js = Inspector.build_ginan_ui_js(yaml_content)

        def on_load_finished(ok: bool):
            if not ok:
                Logger.workflow("⚠️ GinanYAMLInspector page failed to load.")
                return
            webview.page().runJavaScript(ginan_ui_js)

        webview.loadFinished.connect(on_load_finished)

        # Step 8: Fallback download handler - if the save intercept somehow does not
        # fire (e.g. opened outside Ginan-UI then re-used), catch the browser download,
        # merge it into ppp_generated.yaml, and notify the user.
        profile = webview.page().profile()

        def handle_download(download: QWebEngineDownloadRequest):
            """
            Fallback: browser download triggered - ask for save path, then merge back.
            """
            suggested = download.downloadFileName() or "output.yaml"

            save_path, _ = QFileDialog.getSaveFileName(
                dialog,
                "Save Inspector YAML",
                str(Path.home() / suggested)
            )

            if not save_path:
                download.cancel()
                return

            download.setDownloadDirectory(str(Path(save_path).parent))
            download.setDownloadFileName(Path(save_path).name)
            download.accept()

            Logger.workflow(f"💾 GinanYAMLInspector config saved via browser download to: {save_path}")

            # Merge the downloaded file back into ppp_generated.yaml
            try:
                downloaded_text = Path(save_path).read_text(encoding="utf-8")
                self._on_inspector_save(downloaded_text)
            except Exception as e:
                Logger.workflow(f"⚠️ Could not merge GinanYAMLInspector download into ppp_generated.yaml: {e}")

        profile.downloadRequested.connect(handle_download)

        webview.setUrl(QUrl.fromLocalFile(str(INSPECTOR_HTML_PATH)))
        layout.addWidget(webview)

        # Keep a reference so the dialog is not garbage collected while open
        self._inspector_dialog = dialog
        dialog.finished.connect(lambda: setattr(self, "_inspector_dialog", None))

        dialog.show()

    #endregion